apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-sales-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:sqlite:/data/sales-service.db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.sqlite.JDBC"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.community.dialect.SQLiteDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  APP_JWT_EXPIRATION_MINUTES: "120"
  APP_CARS_SERVICE_URL: "http://carsales-api"
